{% set name = "pyorerun" %}
{% set version = "1.5.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/pyorerun/archive/refs/tags/{{ version }}.tar.gz
  sha256: ba685f3395230f1488aca0a3d01f6fdd692c74ee9b161c3b9d2d500f03cb212f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - tk
  run:
    - python >={{ python_min }}
    - ezc3d
    - trc-data-reader
    - biorbd >=1.10.5
    - numpy
    - rerun-sdk =0.27.2
    - trimesh
    - tk
    - imageio
    - imageio-ffmpeg
    - matplotlib-base

test:
  imports:
    - pyorerun
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - python -c "import pyorerun"

about:
  home: https://github.com/pyomeca/pyorerun
  summary: 'Rerun c3d files and biorbd models from python'
  description: |
    Rerun c3d files and biorbd models from python.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/pyomeca/pyorerun

extra:
  recipe-maintainers:
    - Ipuch
