{% set python_min = '3.10' %}
{% set name = "pyorerun" %}
{% set version = "1.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/pyorerun/archive/refs/tags/{{ version }}.tar.gz
  sha256: fe84879adba6b618b40c4c869e8aa90f4bbf4fb30482ee47c62c1f779cbf62c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - tk
  run:
    - python >={{ python_min }}
    - biorbd >=1.11.1
    - ezc3d
    - rerun-sdk =0.21.0
    - numpy
    - trimesh
    - pyomeca
    - tk
    - imageio
    - imageio-ffmpeg

test:
  imports:
    - pyorerun
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - python -c "import pyorerun"

about:
  home: https://github.com/pyomeca/pyorerun
  summary: 'Rerun c3d files and biorbd models from python'
  description: |
    Rerun c3d files and biorbd models from python.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/pyomeca/pyorerun

extra:
  recipe-maintainers:
    - Ipuch
