{% set name = "pyorerun" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/pyorerun/archive/refs/tags/{{ version }}.tar.gz
  sha256: a8b0c09493822e98a695203a70852fcf77f0af4d344e39ef4b5700839a845ebf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
    - tk
  run:
    - python >=3.10
    - biorbd >=1.11.1
    - ezc3d
    - rerun-sdk =0.16.1
    - numpy
    - trimesh
    - pyomeca
    - tk
    - imageio
    - imageio-ffmpeg

test:
  imports:
    - pyorerun
  requires:
    - pip
  commands:
    - python -c "import pyorerun"

about:
  home: https://github.com/pyomeca/pyorerun
  summary: 'Rerun c3d files and biorbd models from python'
  description: |
    Rerun c3d files and biorbd models from python.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/pyomeca/pyorerun

extra:
  recipe-maintainers:
    - Ipuch
